repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--all', '--', '--check']
      - id: cargo-check
      - id: clippy
        name: clippy (default features)
      - id: clippy
        name: clippy (all features)
        args: ['--all-features']
