[package]
name = "iracing-ha-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
iracing = "0.4.1"
iracing-telem = "0.2.1"
rumqttc = "0.24.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
simetry = { version = "0.2.3", default-features = false }
tokio = { version = "1.43.0", features = ["full"] }
yaml-rust = "0.4.5"

[[example]]
name = "get_telemetry"

[[example]]
name = "dump_sample"

[[example]]
name = "iracing_telem_sample"

[[example]]
name = "simetry_sample"
