name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglib2.0-dev \
            libpango1.0-dev \
            libgdk-pixbuf2.0-dev \
            libatk1.0-dev \
            libgtk-3-dev \
            libxdo-dev \
            pkg-config \
            mingw-w64

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cross build --release --target ${{ matrix.target }}
